### ISSUE TITLE
Exception in thread "main"

### ISSUE THREAD

**Issue by RRos53** [tiagorlampert/sAINT#13]
[*] The information above is correct? (y/n): y
Exception in thread "main" java.lang.IllegalArgumentException: Illegal group reference: group index is missing
	at java.util.regex.Matcher.appendReplacement(Matcher.java:819)
	at java.util.regex.Matcher.replaceAll(Matcher.java:955)
	at java.lang.String.replaceAll(String.java:2223)
	at saint.ui.sAINT.replaceWord(sAINT.java:98)
	at saint.ui.sAINT.showGenerator(sAINT.java:365)
	at saint.ui.sAINT.showMenu(sAINT.java:221)
	at saint.ui.sAINT.main(sAINT.java:71)

**Comment by tiagorlampert** [comment]
Hello,
Which java version do you have?

PS: make sure then you followed all steps to configure the environment.
[https://github.com/tiagorlampert/sAINT#how-to-use](https://github.com/tiagorlampert/sAINT#how-to-use)

**Comment by RRos53** [comment]
How check the version?

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by RRos53** [comment]
Have version 1.8.0_171

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by tiagorlampert** [comment]
Did you follow all steps to configure the environment? (They are required)

Make sure that you have installed the necessary dependencies and run the configure.sh.

$ apt install maven default-jdk default-jre openjdk-8-jdk openjdk-8-jre -y
$ apt install zlib1g-dev libncurses5-dev lib32z1 lib32ncurses6 -y

and run

$ git clone https://github.com/tiagorlampert/sAINT.git
$ cd sAINT
$ chmod +x configure.sh
$ ./configure.sh
$ java -jar sAINT.jar

**Comment by Gudvi** [comment]
Hello Friend
I have this problem! 

also
https://github.com/tiagorlampert/sAINT/issues/13#issue-355713191

Script configure.ch launch fails.

>  [ERROR] COMPILATION ERROR : 
> [INFO] -------------------------------------------------------------
> [ERROR] /root/softupload/sAINT/src/main/java/saint/keylogger/Keylogger.java:[73,32] cannot find symbol
>   symbol:   variable countNumber
>   location: class saint.keylogger.Keylogger
> [ERROR] /root/softupload/sAINT/src/main/java/saint/keylogger/Keylogger.java:[78,41] cannot find symbol
>   symbol:   variable booleanScreenshot
>   location: class saint.keylogger.Keylogger
> [ERROR] /root/softupload/sAINT/src/main/java/saint/keylogger/Keylogger.java:[79,34] cannot find symbol
>   symbol:   variable booleanCam
>   location: class saint.keylogger.Keylogger
> [ERROR] /root/softupload/sAINT/src/main/java/saint/keylogger/Keylogger.java:[80,42] cannot find symbol
>   symbol:   variable booleanPersistence
>   location: class saint.keylogger.Keylogger
> [ERROR] /root/softupload/sAINT/src/main/java/saint/keylogger/Keylogger.java:[81,39] cannot find symbol
>   symbol:   variable booleanKeepData
>   location: class saint.keylogger.Keylogger
> [INFO] 5 errors 
> [INFO] -------------------------------------------------------------
> [INFO] ------------------------------------------------------------------------
> [INFO] BUILD FAILURE
> [INFO] ------------------------------------------------------------------------
> [INFO] Total time:  3.242 s
> [INFO] Finished at: 2019-01-09T16:03:56+03:00
> [INFO] ------------------------------------------------------------------------
> [ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.1:compile (default-compile) on project saint: Compilation failure: Compilation failure: 
> [ERROR] /root/softupload/sAINT/src/main/java/saint/keylogger/Keylogger.java:[73,32] cannot find symbol
> [ERROR]   symbol:   variable countNumber
> [ERROR]   location: class saint.keylogger.Keylogger
> [ERROR] /root/softupload/sAINT/src/main/java/saint/keylogger/Keylogger.java:[78,41] cannot find symbol
> [ERROR]   symbol:   variable booleanScreenshot
> [ERROR]   location: class saint.keylogger.Keylogger
> [ERROR] /root/softupload/sAINT/src/main/java/saint/keylogger/Keylogger.java:[79,34] cannot find symbol
> [ERROR]   symbol:   variable booleanCam
> [ERROR]   location: class saint.keylogger.Keylogger
> [ERROR] /root/softupload/sAINT/src/main/java/saint/keylogger/Keylogger.java:[80,42] cannot find symbol
> [ERROR]   symbol:   variable booleanPersistence
> [ERROR]   location: class saint.keylogger.Keylogger
> [ERROR] /root/softupload/sAINT/src/main/java/saint/keylogger/Keylogger.java:[81,39] cannot find symbol
> [ERROR]   symbol:   variable booleanKeepData
> [ERROR]   location: class saint.keylogger.Keylogger
> [ERROR] -> [Help 1]
> [ERROR] 
> [ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
> [ERROR] Re-run Maven using the -X switch to enable full debug logging.
> [ERROR] 
> [ERROR] For more information about the errors and possible solutions, please read the following articles:
> [ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
