### ISSUE TITLE
ArchLinux (Monjaro)

### ISSUE THREAD

**Issue by MrKira34** [tiagorlampert/sAINT#20]
Hi, how to install on ArchLinux?
I install only "maven".
These packages are not in the repository: default-jdk default-jre openjdk-8-jdk openjdk-8-jre zlib1g-dev libncurses5-dev lib32z1 lib32ncurses6

sAINT start up but there are mistakes

```
          +---------------------------------------------------+
    (__)  | WARNING: Use Gmail account only!                  |
 (|)(00)  | E-mail will be sent when it reaches the specified |
  |/(__)\ | number of characters. Optionally you can enable   |
  |_/ _|  | Screenshot, Webcam Capture and Persistence.       |
          +---------------------------------------------------+

 GENERATE SPYWARE
 --------------------------------------------

 [*] Enter your E-mail: ***@gmail.com    
 [*] Enter your Password: ***
 [*] Enable Screenshot (Y/n): y
 [*] Enable WebCam (Y/n): y
 [*] Enable Persistence (Y/n): y
 [*] Keep data on the computer? (Y/n): y
 [*] Enter the number of characters to send E-mail: 500

 +------------------------------------------+
   Email: ***@gmail.com
   Password: ***
   Screenshot: true
   Webcam: true
   Persistence: true
   Keep Data: true
   Number of characters: 500
 +------------------------------------------+

 [*] The information above is correct? (y/n): y

 [*] Compiling...
 [*] Successfully compiled in target/ folder. 

 [*] You would like to generate .EXE using lauch4j? (y/n): y

 [*] Generating...
java.io.FileNotFoundException: launch4j/saint-1.0-jar-with-dependencies.exe (Нет такого файла или каталога)
        at java.base/java.io.FileInputStream.open0(Native Method)
        at java.base/java.io.FileInputStream.open(FileInputStream.java:213)
        at java.base/java.io.FileInputStream.<init>(FileInputStream.java:155)
        at saint.ui.sAINT.copyFile(sAINT.java:168)
        at saint.ui.sAINT.showGenerator(sAINT.java:399)
        at saint.ui.sAINT.showMenu(sAINT.java:221)
        at saint.ui.sAINT.main(sAINT.java:71)
 [*] Failed to generate file! 

 NOTE: Allow access to less secure apps on your gmail account. 
 -> https://www.google.com/settings/security/lesssecureapps 
```

**Comment by viktor02** [comment]
You should install:
pacman -S maven jdk8-openjdk jre8-openjdk ncurses lib32-zlib

**Comment by GoogTech** [comment]
> You should install:
> pacman -S maven jdk8-openjdk jre8-openjdk ncurses lib32-zlib

hey bro I don't receive any emails while the `saint-1.0-jar-with-dependencies.jar` is runing successfully on target host and the `https://myaccount.google.com/lesssecureapps` is turned on.

please help me !

**Comment by viktor02** [comment]
> 
> 
> > You should install:
> > pacman -S maven jdk8-openjdk jre8-openjdk ncurses lib32-zlib
> 
> hey bro I don't receive any emails while the `saint-1.0-jar-with-dependencies.jar` is runing successfully on target host and the `https://myaccount.google.com/lesssecureapps` is turned on.
> 
> please help me !

Sorry, but I'm not a creator and have not used it since the last comment was written, for reasons I have already forgotten =)
