### ISSUE TITLE
Failed to generate file

### ISSUE THREAD

**Issue by BevirAway** [tiagorlampert/sAINT#25]
` [*] Generating...
java.io.FileNotFoundException: launch4j/saint-1.0-jar-with-dependencies.exe (No such file or directory)
        at java.base/java.io.FileInputStream.open0(Native Method)
        at java.base/java.io.FileInputStream.open(FileInputStream.java:219)
        at java.base/java.io.FileInputStream.<init>(FileInputStream.java:157)
        at saint.ui.sAINT.copyFile(sAINT.java:168)
        at saint.ui.sAINT.showGenerator(sAINT.java:399)
        at saint.ui.sAINT.showMenu(sAINT.java:221)
        at saint.ui.sAINT.main(sAINT.java:71)
 [*] Failed to generate file!`

**Comment by BevirAway** [comment]
This error occurs on Kali NetHunter and Win10 Kali Linux

**Comment by heyxmirko** [comment]
Same problem

**Comment by kev6070** [comment]
[!] OS is not supported!
I get this error how do I solve it
